variables:
  VER_PREFIX: '1.0.0'
  EXE_RELEASE_FOLDER: 'Stage\Release'
  DEPLOY_FOLDER: 'Stage\Deploy'

stages:
  - build

build_job:
  stage: build
  script:
    - dotnet publish --configuration Release --nologo -p:PublishReadyToRun=true  -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -p:Version=$env:VER_PREFIX.$env:CI_PIPELINE_IID --runtime win-x64
    - dotnet publish --configuration Release --nologo -p:PublishReadyToRun=false -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -p:Version=$env:VER_PREFIX.$env:CI_PIPELINE_IID --runtime linux-x64
  artifacts:
    paths:
      - '$env:EXE_RELEASE_FOLDER\*\publish\MCBSW*'