variables:
  VER_PREFIX: '1.1.0'
  EXE_RELEASE_FOLDER: 'Stage/Release'
  JFROG_CLI_BUILD_NUMBER: '${VER_PREFIX}.${CI_PIPELINE_IID}'

stages:
  - build

windows:
  stage: 'build'
  dependencies: []
  tags:
  - windows
  script:
    - dotnet publish --configuration Release --nologo -p:PublishReadyToRun=true  -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -p:Version=$JFROG_CLI_BUILD_NUMBER --runtime win-x64
    - dotnet publish --configuration Release --nologo -p:PublishReadyToRun=false -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -p:Version=$JFROG_CLI_BUILD_NUMBER --runtime linux-x64
    - jfrog rt u "$EXE_RELEASE_FOLDER/**/publish/*" mcbesw/${CI_COMMIT_BRANCH}/${JFROG_CLI_BUILD_NUMBER}/ --build-name mcbesw --build-number $JFROG_CLI_BUILD_NUMBER 
    - jfrog rt bag mcbesw $JFROG_CLI_BUILD_NUMBER
    - jfrog rt bp mcbesw $JFROG_CLI_BUILD_NUMBER
    - jfrog rt bce mcbesw $JFROG_CLI_BUILD_NUMBER